default:
  tags:
    - shell

stages:
  - lint
  - build-base
  - build-children

workflow:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'main'"
      changes:
        - "**/*Dockerfile"
        - "backend/Pipfile"
        - "backend/Pipfile.lock"
        - "ml_api/Pipfile"
        - "ml_api/Pipfile.lock"


.dokter_base:
  tags:
    - kube
  allow_failure: true
  image: registry.gitlab.com/gitlab-org/incubation-engineering/ai-assist/dokter/dokter:latest
  stage: lint
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    when: always
    paths:
      - "dokter-$CI_COMMIT_SHA.json"


backend-dokter:
  extends: .dokter_base
  script:
    - dokter -d backend/Dockerfile -s

ml_api-dokter:
  extends: .dokter_base
  script:
    - cd ml_api
    - dokter -d Dockerfile -s
    - dokter -d base_x86_64.Dockerfile -s


build_api_base:
  stage: build-base
  needs: []
  script:
    - cd ml_api
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build -t $CI_REGISTRY/docker/obico-server/api-base:latest -f base_x86_64.Dockerfile .
    - docker push $CI_REGISTRY/docker/obico-server/api-base:latest

build_api_child:
  stage: build-children
  needs:
    - job: build_api_base
  script:
    - cd ml_api
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build -t $CI_REGISTRY/docker/obico-server/api:latest -f Dockerfile .
    - docker push $CI_REGISTRY/docker/obico-server/api:latest

build_backend_child:
  stage: build-children
  needs: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build -t $CI_REGISTRY/docker/obico-server/backend:latest -f backend/Dockerfile .
    - docker push $CI_REGISTRY/docker/obico-server/backend:latest
