default:
  tags:
    - shell

stages:
  - build-base
  - build-children

build_api_base:
  stage: build-base
  needs: []
  script:
    - cd ml_api
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/docker/obico-server:api-base-latest -f Dockerfile.base_x86_64 .
    - docker push $CI_REGISTRY/docker/obico-server:api-base-latest

build_app_base:
  stage: build-base
  needs: []
  script:
    - cd backend
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/docker/obico-server:backend-base-latest -f Dockerfile.base .
    - docker push $CI_REGISTRY/docker/obico-server:backend-base-latest

build_api_child:
  stage: build-children
  needs:
    - job: build_api_base
  script:
    - cd ml_api
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/docker/obico-server:api-latest -f Dockerfile .
    - docker push $CI_REGISTRY/docker/obico-server:api-latest

build_backend_child:
  stage: build-children
  needs:
    - job: build_app_base
  script:
    - cd backend
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/docker/obico-server:backend-latest -f Dockerfile .
    - docker push $CI_REGISTRY/docker/obico-server:backend-latest
build_frontend_child:
  stage: build-children
  needs:
    - job: build_app_base
  script:
    - echo hello
