version: '2.4'

x-web-defaults:
  &web-defaults
  restart: unless-stopped
  image: glregistry.wizzlehq.org/docker/obico-server/backend:latest
  volumes:
    - ./backend:/app
    - ./frontend:/frontend
  depends_on:
    - redis
  environment:
    EMAIL_HOST: '${EMAIL_HOST-}'
    EMAIL_HOST_USER: '${EMAIL_HOST_USER-}'
    EMAIL_HOST_PASSWORD: '${EMAIL_HOST_PASSWORD-}'
    EMAIL_PORT: '${EMAIL_PORT-587}'
    EMAIL_USE_TLS: '${EMAIL_USE_TLS-True}'
    DEFAULT_FROM_EMAIL: '${DEFAULT_FROM_EMAIL-changeme@example.com}'
    DEBUG: '${DEBUG-False}' # Don't set DEBUG to True unless you know what you are doing. Otherwise the static files will be cached in browser until hard-refresh
    SITE_USES_HTTPS: 'True'
    SITE_IS_PUBLIC: 'True'
    SOCIAL_LOGIN: '${SOCIAL_LOGIN-False}'
    REDIS_URL: '${REDIS_URL-redis://redis:6379}'
    DATABASE_URL: '${DATABASE_URL-sqlite:////app/db.sqlite3}'
    INTERNAL_MEDIA_HOST: '${INTERNAL_MEDIA_HOST-http://obico-web:3334}'
    ML_API_HOST: '${ML_API_HOST-http://ml_api:3333}'
    ACCOUNT_ALLOW_SIGN_UP: '${ACCOUNT_ALLOW_SIGN_UP-False}'
    WEBPACK_LOADER_ENABLED: '${WEBPACK_LOADER_ENABLED-False}'
    OCTOPRINT_TUNNEL_PORT_RANGE: '${OCTOPRINT_TUNNEL_PORT_RANGE-15853-15873}'
    TELEGRAM_BOT_TOKEN: '${TELEGRAM_BOT_TOKEN-}'
    TWILIO_ACCOUNT_SID: '${TWILIO_ACCOUNT_SID-}'
    TWILIO_AUTH_TOKEN: '${TWILIO_AUTH_TOKEN-}'
    TWILIO_FROM_NUMBER: '${TWILIO_FROM_NUMBER-}'
    SENTRY_DSN: '${SENTRY_DSN-}'
    PUSHOVER_APP_TOKEN: '${PUSHOVER_APP_TOKEN-}'
    SLACK_CLIENT_ID: '${SLACK_CLIENT_ID-}'
    SLACK_CLIENT_SECRET: '${SLACK_CLIENT_SECRET-}'
    VERSION:


services:
  ml_api:
    hostname: ml_api
    restart: unless-stopped
    image: glregistry.wizzlehq.org/docker/obico-server/api:latest
    environment:
      DEBUG: 'True'
      FLASK_APP: 'server.py'
      #ML_API_TOKEN:
      HAS_GPU: 'False'

  obico-web:
    <<: *web-defaults
    hostname: obico-web
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.obico-web.tls=true
      - "traefik.http.services.obico-web.loadbalancer.server.port=3334"
      - "traefik.http.routers.obico-web.entrypoints=websecure"
      - traefik.http.routers.obico-web.rule=Host("spaghetti.wizzlehq.org")
      - traefik.http.routers.obico-web.tls.certresolver=myresolver
    networks:
      - proxynet
    ports:
      - "3334:3334"
      - "${OCTOPRINT_TUNNEL_PORT_RANGE-15853-15873}:3334"
    depends_on:
      - ml_api

  tasks:
    <<: *web-defaults
    hostname: tasks
    command: pipenv run celery -A config worker --beat -l info -c 2 -Q realtime,celery

  redis:
    restart: unless-stopped
    image: redis:5.0-alpine

networks:
  proxynet:
    name: proxy_net
    external: true
